name: slugify
description: Slugify a given path to use as an identifier

inputs:
  path:
    description: The path to slugify
    required: true
  prefix:
    description: Optional prefix to prepend to the slug
    default: ""
  suffix:
    description: Optional suffix to append to the slug
    default: ""

outputs:
  slug:
    description: The slugified path
    value: ${{ inputs.prefix }}${{ steps.slug.outputs.slug }}${{ inputs.suffix }}

runs:
  using: composite
  steps:
    - name: Run script
      id: slug
      shell: bash
      run: ${{ github.action_path }}/script.sh ${{ inputs.path }}
